/control/verbose 2
/run/verbose 2
/event/verbose 2
/tracking/verbose 2

# Use the OpenGL visualization driver
/vis/open OGL 600x600-0+0

# Draw the detector geometry
/vis/drawVolume

# Set visualization attributes
/vis/viewer/set/viewpointThetaPhi 90 180
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/vis/viewer/set/background black
